version: "3"

services:
  cat-db:
    container_name: cat-db
    image: postgres

    environment:
      - POSTGRES_DB=CAT_DB
      - POSTGRES_USER=CAT_USER
      - POSTGRES_PASSWORD=CAT_PASSWORD

    volumes:
      - ".:/postgres/data"

    ports:
      - 5432:5432